"""
Problem #2
Write a program that calculates the profit generated by a movie theatre for different ticket classes.

For VIP tickets, the profit is 30% of the ticket price + Rs120 for every ticket sold.
For General tickets, the profit is 20% of the ticket price + Rs80 for every ticket sold.
For Matinee show tickets, the profit is a flat 15% of the ticket price.
Input: Ticket price and number of tickets sold for each ticket class.
Output: Calculate and print the total revenue generated by the theatre in a day.
"""
def ProfitOfTickets(TicketClass,ticketsBooked,ticketPrice):
    if TicketClass =="VIP":
        profitPercentage=0.3
        profit=(profitPercentage*ticketPrice+120)*ticketsBooked
        return(profit)
    elif TicketClass == "General":
        profitPercentage=0.2
        profit=(profitPercentage*ticketPrice+80)*ticketsBooked
        return(profit)
    else:
        profitPercentage=0.15
        profit=(profitPercentage*ticketPrice)*ticketsBooked
        return(profit)



def calculatePercentage(profit,totalProfit):
    profitPercentage=round((profit/totalProfit)*100,2)
    return (profitPercentage)


vipTicketsBooked=int(input("Enter the no of Vip tickets booked:"))
vipTicketsPrice=float(input("Enter the price of the vip tickets:"))
profitOfVIPTickets=ProfitOfTickets("VIP",vipTicketsBooked,vipTicketsPrice)

generalTicketsBooked=int(input("Enter the no of general tickets booked:"))
generalTicketsPrice=float(input("Enter the price of the general tickets:"))
profitOfGeneralTickets=ProfitOfTickets("General",generalTicketsBooked,generalTicketsPrice)

matnieeTicketsBooked=int(input("Enter the no of Matinee tickets booked:"))
matnieeTicketProfit=float(input("Enter the price of the Matinee tickets:"))
profitOfMatineeTickets=ProfitOfTickets("Matinee",matnieeTicketsBooked,matnieeTicketProfit)

totalProfit=profitOfGeneralTickets+profitOfMatineeTickets+profitOfVIPTickets
PercentageOfVipprofit=calculatePercentage(profitOfVIPTickets,totalProfit)
percentageOfGeneralProfit=calculatePercentage(profitOfGeneralTickets,totalProfit)
percentageOfMatineeProfit=calculatePercentage(profitOfMatineeTickets,totalProfit)
totaltickets=vipTicketsBooked+generalTicketsBooked+matnieeTicketsBooked

print("\tSUMMARY\t")
print(f"Total tickets Booked:{totaltickets}")
print(f"No.Of Vip tickets booked:{vipTicketsBooked}")
print(f"Profit earned from 'Vip class':{profitOfVIPTickets}\nPercentage of profit earned from 'VIP class':{PercentageOfVipprofit}\n")
print(f"No.Of General tickets Booked:{generalTicketsBooked}")
print(f"Profit earned from 'General class':{profitOfGeneralTickets}\nPercentage of profit earned from 'General class':{percentageOfGeneralProfit}\n")
print(f"No.Of Matniee tickets Booked:{matnieeTicketsBooked}")
print(f"Profit earned from 'Matniee show':{matnieeTicketProfit}\nPercentage of profit earned from 'Matniee show':{percentageOfMatineeProfit}\n")
print(f"total Profit Earned by the theatre:{round(totalProfit,2)}")

"""
OP:
Enter the no of Vip tickets booked:50 
Enter the price of the vip tickets:400
Enter the no of general tickets booked:50
Enter the price of the general tickets:300
Enter the no of Matinee tickets booked:30
Enter the price of the Matinee tickets:150
        SUMMARY
Total tickets Booked:130
No.Of Vip tickets booked:50
Profit earned from 'Vip class':12000.0
Percentage of profit earned from 'VIP class':60.99

No.Of General tickets Booked:50
Profit earned from 'General class':7000.0
Percentage of profit earned from 'General class':35.58

No.Of Matniee tickets Booked:30
Profit earned from 'Matniee show':150.0
Percentage of profit earned from 'Matniee show':3.43

total Profit Earned by the theatre:19675.0
"""